### ISSUE TITLE
Make anything marked with data-stepper-next go to next by default.

### ISSUE THREAD

**Issue by ghost** [ahlechandre/mdl-stepper#23]
It seems odd why this isn't the default behaviour. I think it should be the same for data-stepper-cancel and other actions as well. Or is there a way to make this the default behaviour?

**Comment by axdemelas** [comment]
What is the default behavior of "next" action? What is the default behavior of "cancel" action?

The custom events and the methods are thought to give you a power to process step by step your data before applying each user action with the component.

For instance, are not every time user clicks on "next" button that stepper should advance to the next. What if your current step has a invalid field? You would continue moving forward, then you process all steps data at once (at the end of stepper) and finds the invalid field, then you brings the user to the first step where is located the error? What if your current step has dynamic input fields that needs to be loaded asynchronously and depends from a user choice on previous step? When you calls the function to get the server response?

What I mean is that we cannot have a default behavior because it does not exists. We need to be flexible and using the custom events and stepper/step methods we are able to handle every case at any point.

### Example

``` js
const Stepper = document.querySelector('.mdl-stepper').MaterialStepper;
const step = document.querySelector('.mdl-step'); // The first step.
const field = step.querySelector('input'); // The input field that needs to be validated.

step.addEventListener('onstepnext', () => {
  if (field.value.length) {
     // Ok, the field is valid and we can move forward.
     Stepper.next();
  } else {
    // Ops, the field is invalid and we cannot move forward.
    Stepper.error('Please, complete the field.');
  } 
});
```

### Default behavior polyfill

If you really needs a way to make the "default behavior", you can use something like this:

``` js
const stepperElement = document.querySelector('.mdl-stepper');
const Stepper = stepperElement.MaterialStepper;
const nextButtons = stepperElement.querySelectorAll('[data-stepper-next]');

for (let i = 0; i < nextButtons.length; i++) {
   nextButtons[i].addEventListener('click', () => {
      // Put your default behavior.
      Stepper.next();
   });
}
```

Make that for other actions as well.

**Comment by ghost** [comment]
Thanks!
